version: '3.8'
services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    command: ["mongod","--replSet","rs0","--bind_ip_all"]
    volumes:
      - ./data/mongo1:/data/db
    ports:
      - "27017:27017"

